//
//  DiagnosticReport.swift
//  UsageMeter
//
//  Created by f-is-h on 2025-11.
//  Copyright © 2025 f-is-h. All rights reserved.
//

import Foundation

// MARK: - DiagnosticStep

/// Result of a single test step
struct DiagnosticStep: Codable {
    let name: String
    let success: Bool
    let httpStatusCode: Int?
    let responseTime: Double?
    let responseType: ResponseType
    let errorType: DiagnosticErrorType?
    let errorDescription: String?
    let responseHeaders: [String: String]
    let responseBodyPreview: String?
    let cloudflareChallenge: Bool
    let cfMitigated: Bool
    /// Extra notes, the JWT expiry for instance
    let notes: String?

    enum ResponseType: String, Codable {
        case json = "JSON"
        case html = "HTML"
        case unknown = "Unknown"
    }
}

// MARK: - ProviderDiagnosticResult

/// Diagnostic result for one provider
struct ProviderDiagnosticResult: Codable {
    let providerType: ProviderType
    /// Redacted credential key value pairs, for the report
    let credentials: [String: String]
    let steps: [DiagnosticStep]
    let success: Bool
    let errorType: DiagnosticErrorType?
    let diagnosis: String
    let suggestions: [String]
    let confidence: ConfidenceLevel

    enum ConfidenceLevel: String, Codable {
        case high = "High"
        case medium = "Medium"
        case low = "Low"
    }
}

// MARK: - DiagnosticReport

/// Top level diagnostic report (provider agnostic)
struct DiagnosticReport: Codable {

    // MARK: - Basic info

    let timestamp: Date
    let appVersion: String
    let osVersion: String
    let architecture: String
    let locale: String

    // MARK: - Configuration

    let refreshMode: String
    let refreshInterval: String?
    let displayMode: String

    // MARK: - Provider diagnostic results

    let providers: [ProviderDiagnosticResult]

    // MARK: - Computed properties

    var overallSuccess: Bool {
        !providers.isEmpty && providers.allSatisfy { $0.success }
    }

    // MARK: - Markdown output

    func toMarkdown() -> String {
        var report = """
        # Usage Meter Diagnostic Report

        **⚠️ PRIVACY NOTICE**: All sensitive information has been automatically redacted.
        **✅ Safe to share**: This report contains no complete credentials or personal data.

        ---

        ## Test Result

        """
        report += "**Status**: \(overallSuccess ? "✅ All Passed" : "❌ Issues Detected")  \n"
        report += "**Timestamp**: \(formatTimestamp())  \n"
        report += """

        ---

        ## System Information

        - **App Version**: \(appVersion)
        - **macOS Version**: \(osVersion)
        - **Architecture**: \(architecture)
        - **Locale**: \(locale)

        ## Configuration

        - **Refresh Mode**: \(refreshMode)
        """

        if let interval = refreshInterval {
            report += "\n- **Refresh Interval**: \(interval)"
        }

        report += "\n- **Display Mode**: \(displayMode)\n"
        report += "\n---\n"

        for result in providers {
            report += renderProviderSection(result)
        }

        report += """

        ---

        ## Additional Information

        - Report generated by Usage Meter v\(appVersion)
        - For help, visit: https://github.com/sirpooya/osx-usage-meter/issues
        - Include this report when reporting issues

        """
        return report
    }

    private func renderProviderSection(_ result: ProviderDiagnosticResult) -> String {
        let title: String
        switch result.providerType {
        case .claude: title = "## Claude Diagnostic"
        case .codex: title = "## Codex (ChatGPT) Diagnostic"
        }

        var section = "\n\(title)\n\n"
        section += "**Status**: \(result.success ? "✅ Success" : "❌ Failed")  \n"

        if !result.credentials.isEmpty {
            section += "\n### Credentials\n\n"
            for (key, value) in result.credentials.sorted(by: { $0.key < $1.key }) {
                section += "- **\(key)**: `\(value)` (redacted)\n"
            }
        }

        for step in result.steps {
            section += renderStepSection(step)
        }

        section += "\n### Analysis\n\n"
        section += "**Diagnosis**: \(result.diagnosis)  \n"
        section += "**Confidence**: \(result.confidence.rawValue)  \n"

        if !result.suggestions.isEmpty {
            section += "\n#### Suggested Actions\n\n"
            for (index, suggestion) in result.suggestions.enumerated() {
                section += "\(index + 1). \(suggestion)\n"
            }
        }

        section += "\n---\n"
        return section
    }

    private func renderStepSection(_ step: DiagnosticStep) -> String {
        var section = "\n### \(step.name)\n\n"
        section += "**Result**: \(step.success ? "✅ Pass" : "❌ Fail")  \n"

        if let statusCode = step.httpStatusCode {
            section += "**HTTP Status**: \(statusCode)  \n"
        }

        if let responseTime = step.responseTime {
            section += "**Response Time**: \(String(format: "%.0f ms", responseTime))  \n"
        }

        section += "**Content Type**: \(step.responseType.rawValue)  \n"

        if step.cloudflareChallenge {
            section += "**Cloudflare Challenge**: ⚠️ Detected  \n"
        }

        if step.cfMitigated {
            section += "**CF-Mitigated Header**: Present  \n"
        }

        if let notes = step.notes, !notes.isEmpty {
            section += "**Notes**: \(notes)  \n"
        }

        if let errorType = step.errorType {
            section += "**Error Type**: \(errorType.rawValue)  \n"
        }

        if let errorDesc = step.errorDescription {
            section += "**Error**: \(errorDesc)  \n"
        }

        if !step.responseHeaders.isEmpty {
            section += "\n**Response Headers**:\n```\n"
            for (key, value) in step.responseHeaders.sorted(by: { $0.key < $1.key }) {
                section += "\(key): \(value)\n"
            }
            section += "```\n"
        }

        if let preview = step.responseBodyPreview, !preview.isEmpty {
            section += "\n**Response Body** (first 500 characters):\n```\n\(preview)\n```\n"
        }

        return section
    }

    private func formatTimestamp() -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
        formatter.timeZone = TimeZone.current
        return formatter.string(from: timestamp)
    }
}

// MARK: - DiagnosticErrorType

/// Diagnostic error types
enum DiagnosticErrorType: String, Codable {
    // Claude
    case cloudflareBlocked = "Cloudflare Challenge"
    case authenticationFailed = "Authentication Failed"
    case networkError = "Network Error"
    case decodingError = "Data Parsing Error"
    case invalidCredentials = "Invalid Credentials"
    case timeout = "Request Timeout"
    case unknown = "Unknown Error"
    // Codex
    case sessionTokenInvalid = "Codex Session Token Invalid"
    case accessTokenExpired = "Codex Access Token Expired"
    case usageEndpointFailed = "Codex Usage Endpoint Failed"
    case ssrBootstrapFailed = "Codex SSR Bootstrap Failed"
}

// MARK: - English Diagnostic Messages (for export only, not localized)

/// English copy for the diagnostic report (for export, deliberately unlocalized so the language stays consistent)
enum DiagnosticMessage {

    // MARK: - Claude

    static let diagnosisSuccess = "Connection is working properly. API returned valid usage data."
    static let diagnosisCloudflare = "Request was blocked by Cloudflare security system. This may be due to IP reputation or network configuration."
    static let diagnosisDecoding = "Server returned data but it couldn't be parsed. This usually means credentials are incorrect or don't match."
    static let diagnosisNetwork = "Network connection failed. Please check your internet connection."
    static let diagnosisNoCredentials = "Authentication credentials are not configured."
    static let diagnosisInvalidUrl = "Invalid Organization ID format."
    static let diagnosisUnknown = "Unknown error occurred. Please export and share this report with developers."

    static let suggestionSuccess = "Everything is working correctly. No action needed."
    static let suggestionVisitBrowser = "Visit claude.ai in your browser and complete any security challenges"
    static let suggestionWaitAndRetry = "Wait 5-10 minutes and try again"
    static let suggestionCheckVPN = "Check if VPN or proxy is affecting the connection"
    static let suggestionUseSmartMode = "Use Smart Refresh mode to reduce request frequency"
    static let suggestionVerifyCredentials = "Verify that Organization ID and Session Key are correct"
    static let suggestionUpdateSessionKey = "Your Session Key may have expired. Please update it from browser"
    static let suggestionCheckBrowser = "Verify you can access claude.ai/settings/usage in browser"
    static let suggestionCheckInternet = "Check your internet connection"
    static let suggestionCheckFirewall = "Check firewall or antivirus settings"
    static let suggestionRetryLater = "Try again later"
    static let suggestionConfigureAuth = "Please configure Organization ID and Session Key in the fields above"
    static let suggestionCheckOrgId = "Check if Organization ID format is correct (should be a UUID)"
    static let suggestionExportAndShare = "Export this diagnostic report and share it on GitHub Issues"
    static let suggestionContactSupport = "Contact developer for help at github.com/sirpooya/osx-usage-meter/issues"

    // MARK: - Codex

    static let diagnosisCodexSuccess = "Connection is working properly. Codex API returned valid usage data."
    static let diagnosisCodexNoCredentials = "Codex session token is not configured."
    static let diagnosisCodexSessionInvalid = "Codex session token is invalid or expired. Please log in again."
    static let diagnosisCodexSessionCloudflare = "Session endpoint was blocked by Cloudflare. ChatGPT may have flagged your IP."
    static let diagnosisCodexAccessExpired = "Access token was obtained but the usage endpoint returned 401. The cached access token may be expired."
    static let diagnosisCodexSsrRecovered = "Session endpoint failed but SSR refresh succeeded. Restarting the app should restore functionality."
    static let diagnosisCodexSsrFailed = "Both session endpoint and SSR refresh failed. The session token has likely expired."
    static let diagnosisCodexUsageFailed = "Session token is valid but the usage API returned an unexpected response."
    static let diagnosisCodexUsageCloudflare = "Usage endpoint was blocked by Cloudflare. ChatGPT may have flagged your IP."

    static let suggestionCodexRelogin = "Please log in to Codex again from Settings"
    static let suggestionCodexRestartApp = "Restart the app — it will automatically refresh the access token via SSR"
    static let suggestionCodexCheckChatGPTBrowser = "Visit chatgpt.com in your browser to complete any security challenges"
    static let suggestionCodexClearWebViewCache = "Try clearing the WebView cache from Settings and logging in again"
}
